version: '3.8'

services:
  web:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my-blog-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - my-blog-network

networks:
  my-blog-network:
    driver: bridge
